services:
  - type: web
    name: watch-market
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --worker-class gthread --threads 4 'run:app'
    envVars:
      - key: PYTHON_VERSION
        value: 3.9
      - key: REDDIT_CLIENT_ID
        sync: false
      - key: REDDIT_CLIENT_SECRET
        sync: false 